/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package my.Projeto_ED;

/**
 *
 * @author taiscguerra
 * 
 */
import java.util.ArrayList;
import java.util.Iterator;
import javax.swing.*;

public class Menu2UI extends javax.swing.JFrame {

    /**
     * Creates new form Menu2UI
     */
    public Menu2UI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    String tipoLista;
    ListaSeq lista = new ListaSeq();
    ListaEncadeada listaEnc = new ListaEncadeada();
    ArrayList<JLabel> quadrados = new ArrayList<JLabel>();
    ArrayList<JLabel> traco = new ArrayList<JLabel>();
   

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Adicionar_btn = new javax.swing.JButton();
        elem_busca = new javax.swing.JTextField();
        pos_busca = new javax.swing.JTextField();
        btn_busca_pos = new javax.swing.JButton();
        btn_bus_elem = new javax.swing.JButton();
        resultadoelemento = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        campo_pos = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        campo_elem = new javax.swing.JTextField();
        Remover_btn = new javax.swing.JButton();
        labelaviso = new javax.swing.JLabel();
        resultpos = new javax.swing.JLabel();
        label_result = new javax.swing.JLabel();
        campo0 = new javax.swing.JLabel();
        campo1 = new javax.swing.JLabel();
        campo2 = new javax.swing.JLabel();
        campo3 = new javax.swing.JLabel();
        campo4 = new javax.swing.JLabel();
        campo5 = new javax.swing.JLabel();
        campo6 = new javax.swing.JLabel();
        campo7 = new javax.swing.JLabel();
        close = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Adicionar_btn.setText("adicionar");
        Adicionar_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Adicionar_btnActionPerformed(evt);
            }
        });

        elem_busca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                elem_buscaActionPerformed(evt);
            }
        });

        btn_busca_pos.setText("buscar por posição");
        btn_busca_pos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_busca_posActionPerformed(evt);
            }
        });

        btn_bus_elem.setText("buscar por elemento");
        btn_bus_elem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_bus_elemActionPerformed(evt);
            }
        });

        resultadoelemento.setText("Resultado:");

        jLabel3.setText("Resultado:");

        campo_pos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campo_posActionPerformed(evt);
            }
        });

        jLabel8.setText("Posição:");

        jLabel9.setText("Elemento:");

        Remover_btn.setText("remover");
        Remover_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Remover_btnActionPerformed(evt);
            }
        });

        labelaviso.setFont(new java.awt.Font("Cantarell", 1, 14)); // NOI18N

        campo0.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.foreground"));
        campo0.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        campo0.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(175, 15, 29)));

        campo1.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.foreground"));
        campo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        campo1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(238, 37, 12)));

        campo2.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.foreground"));
        campo2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        campo2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(237, 112, 23)));

        campo3.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.foreground"));
        campo3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        campo3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(251, 249, 10)));

        campo4.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.foreground"));
        campo4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        campo4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(95, 255, 0)));

        campo5.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.foreground"));
        campo5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        campo5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(55, 133, 23)));

        campo6.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.foreground"));
        campo6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        campo6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(24, 192, 246)));

        campo7.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.foreground"));
        campo7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        campo7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(33, 24, 229)));

        close.setText("fechar");
        close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(labelaviso, javax.swing.GroupLayout.PREFERRED_SIZE, 485, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(campo0, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(campo1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(campo2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(3, 3, 3)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(campo3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(campo4, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel11)
                                .addGap(8, 8, 8)
                                .addComponent(campo5, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(campo6, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(campo7, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 89, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(18, 18, 18)
                                .addComponent(campo_pos, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(Adicionar_btn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Remover_btn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btn_busca_pos, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(pos_busca, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(resultpos, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(49, 49, 49)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btn_bus_elem, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(elem_busca, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(resultadoelemento)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(label_result))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(close)
                                                .addGap(15, 15, 15))))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(campo_elem, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(campo_pos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel8))
                            .addComponent(campo0, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(campo1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(campo2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(campo3, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(campo4, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(campo5, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(campo6, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(campo7, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jLabel5))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLabel6))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLabel7))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jLabel10))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLabel11))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLabel12))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLabel1)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campo_elem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Adicionar_btn)
                        .addGap(29, 29, 29)
                        .addComponent(Remover_btn))
                    .addComponent(labelaviso, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 96, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_busca_pos)
                    .addComponent(pos_busca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_bus_elem)
                    .addComponent(elem_busca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(resultpos, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel3)
                                .addComponent(resultadoelemento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(label_result)))
                        .addGap(38, 38, 38))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(close)
                        .addGap(24, 24, 24))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void escolherLista(String lista) {
        this.tipoLista = lista;

    }
    
    public final void criarLista(){
     
        
        
        quadrados.add(campo0);
        quadrados.add(campo1);
        quadrados.add(campo2);
        quadrados.add(campo3);
        quadrados.add(campo4);
        quadrados.add(campo5);
        quadrados.add(campo6);
        quadrados.add(campo7);
        
        traco.add(jLabel1);
        traco.add(jLabel5);
        traco.add(jLabel6);
        traco.add(jLabel7);
        traco.add(jLabel12);
        traco.add(jLabel11);
        traco.add(jLabel10);
        
        
       
        
    }



    private void Adicionar_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Adicionar_btnActionPerformed

        if (tipoLista == "Lista Sequencial") {
 
            int elem = Integer.parseInt(campo_elem.getText());
            int pos = Integer.parseInt(campo_pos.getText());
            
            if (pos >= 8){
                
             labelaviso.setText("Você digitou uma posição maior que o array");
             return;
                
            }
            
           
            
            lista.Insere(pos, elem);
            int n = 0;
            int t = 0;
            
            while(t < 8){
                
                quadrados.get(t).setText(null);
                t++;
                
            }
           
            while (n < lista.tamanhoLista()) {
                String elemento = Integer.toString(lista.Elemento(n));
                quadrados.get(n).setText(elemento);
              
                n++;

            }
            
            resultpos.setText(null);
            
        } else {
            int j = 0;
            while(j < traco.size()){
                
                traco.get(j).setText("-->");
                j++;
                
            }

            int elem = Integer.parseInt(campo_elem.getText());
            int pos = Integer.parseInt(campo_pos.getText());
            
            if (pos >= 8){
                
             labelaviso.setText("Uma posição maior que a lista foi digitada!");
             return;
                
            }
            
            
            
            listaEnc.Insere(elem, pos);
            int n = 0;
            int t = 0;
            
            while(t < 8){
                
                quadrados.get(t).setText(null);
                t++;
                
            }
            
            while (n < listaEnc.getTamanho()) {
                String elemento = Integer.toString(listaEnc.Elemento(n));
                quadrados.get(n).setText(elemento);
               
                n++;

            }
        }

    }//GEN-LAST:event_Adicionar_btnActionPerformed

    private void btn_bus_elemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_bus_elemActionPerformed
        
        
        String elem_buscaStr = elem_busca.getText();
        int elem_buscaInt = Integer.parseInt(elem_buscaStr);

        if (tipoLista == "Lista Sequencial"){
        label_result.setText(Integer.toString(lista.Posicao(elem_buscaInt)));
        }
        else {
        label_result.setText(Integer.toString(listaEnc.Posicao(elem_buscaInt)));
        }
    }//GEN-LAST:event_btn_bus_elemActionPerformed

    private void elem_buscaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_elem_buscaActionPerformed

    }//GEN-LAST:event_elem_buscaActionPerformed

    private void campo_posActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campo_posActionPerformed

    }//GEN-LAST:event_campo_posActionPerformed

    private void btn_busca_posActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_busca_posActionPerformed
        String pos_buscaStr = pos_busca.getText();
        int pos_buscaInt = Integer.parseInt(pos_buscaStr);

        if (tipoLista == "Lista Sequencial"){
        resultpos.setText(Integer.toString(lista.Elemento(pos_buscaInt)));
        }
        
        else {
         resultpos.setText(Integer.toString(listaEnc.Elemento(pos_buscaInt)));
        }
    }//GEN-LAST:event_btn_busca_posActionPerformed

    private void Remover_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Remover_btnActionPerformed
         if (tipoLista == "Lista Sequencial") {           
            int pos = Integer.parseInt(campo_pos.getText());
            
            if (pos >= 8){
                
             labelaviso.setText("Você digitou uma posição maior que o array");
             return;
                
            }
            
            if (pos > lista.tamanhoLista()){
                
                 labelaviso.setText("A posição está vazia!");
                 return;
                
            }
            
            lista.Remove(pos);
            int n = 0;
            int t = 0;
            while(t < 8){
                
                quadrados.get(t).setText(null);
                t++;
            }
            
            while (n < lista.tamanhoLista()) {
                String elemento = Integer.toString(lista.Elemento(n));
                
                quadrados.get(n).setText(elemento);
                n++;

            }
        } else {
            
            int pos = Integer.parseInt(campo_pos.getText());
            
            if (pos >= 8){
                
             labelaviso.setText("Você digitou uma posição maior que o array");
             return;
                
            }
            
            if (Integer.toString(listaEnc.Elemento(pos)) == null){
                
                 labelaviso.setText("A posição está vazia!");
                 return;
                
            }
            
            listaEnc.Remove(pos);
            int n = 0;
            int t = 0;
            while(t < 8){
                
                quadrados.get(t).setText(null);
                t++;
            }
            
            while (n < listaEnc.getTamanho()) {
                String elemento = Integer.toString(listaEnc.Elemento(n));
                quadrados.get(n).setText(elemento);
                n++;

            }
         }
    }//GEN-LAST:event_Remover_btnActionPerformed

    private void closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeActionPerformed

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Projeto_ED_UI().setVisible(true);
                
                
                
                
            }
            
            
        });
        dispose();
    
       
        
    }//GEN-LAST:event_closeActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Adicionar_btn;
    private javax.swing.JButton Remover_btn;
    private javax.swing.JButton btn_bus_elem;
    private javax.swing.JButton btn_busca_pos;
    private javax.swing.JLabel campo0;
    private javax.swing.JLabel campo1;
    private javax.swing.JLabel campo2;
    private javax.swing.JLabel campo3;
    private javax.swing.JLabel campo4;
    private javax.swing.JLabel campo5;
    private javax.swing.JLabel campo6;
    private javax.swing.JLabel campo7;
    private javax.swing.JTextField campo_elem;
    private javax.swing.JTextField campo_pos;
    private javax.swing.JButton close;
    private javax.swing.JTextField elem_busca;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel label_result;
    private javax.swing.JLabel labelaviso;
    private javax.swing.JTextField pos_busca;
    private javax.swing.JLabel resultadoelemento;
    private javax.swing.JLabel resultpos;
    // End of variables declaration//GEN-END:variables
}
