/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.

 */


package my.Projeto_ED;

import java.util.ArrayList;
import javax.swing.JLabel;

/**
 *
 * @author taiscguerra
 * 
 */



public class Pilha_Fila_UI extends javax.swing.JFrame {

    /**
     * Creates new form Pilha_Fila_UI
     */
    public Pilha_Fila_UI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
   
    String tipoLista;
    ArrayList<JLabel> quadrados = new ArrayList<JLabel>();
    Pilha pilha = new Pilha();
    FilaEncadeada fila = new FilaEncadeada();
     
    
    
    public final void criarLista(){
     
        
        
        quadrados.add(campo0);
        quadrados.add(campo1);
        quadrados.add(campo2);
        quadrados.add(campo3);
        quadrados.add(campo4);
        quadrados.add(campo5);
        quadrados.add(campo6);
        quadrados.add(campo7);
        quadrados.add(campo8);
       
    }
    public void escolherLista(String lista){
       this.tipoLista = lista;
       
    }
    
    
    
    
    
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_add_pf = new javax.swing.JButton();
        btn_rem_pf = new javax.swing.JButton();
        campo_elemPF = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btn_primElem = new javax.swing.JButton();
        campo0 = new javax.swing.JLabel();
        campo1 = new javax.swing.JLabel();
        campo2 = new javax.swing.JLabel();
        campo3 = new javax.swing.JLabel();
        campo4 = new javax.swing.JLabel();
        campo5 = new javax.swing.JLabel();
        campo6 = new javax.swing.JLabel();
        campo7 = new javax.swing.JLabel();
        campo8 = new javax.swing.JLabel();
        labelcampo1 = new javax.swing.JLabel();
        labelaviso = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btn_add_pf.setText("adicionar");
        btn_add_pf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_add_pfActionPerformed(evt);
            }
        });

        btn_rem_pf.setText("remover");
        btn_rem_pf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_rem_pfActionPerformed(evt);
            }
        });

        campo_elemPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campo_elemPFActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("URW Gothic L", 1, 24)); // NOI18N
        jLabel1.setText("Pilha/Fila");

        jLabel2.setText("Elemento:");

        btn_primElem.setText("primeiro elemento");
        btn_primElem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_primElemActionPerformed(evt);
            }
        });

        campo0.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.foreground"));
        campo0.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        campo0.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(175, 15, 29)));

        campo1.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.foreground"));
        campo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        campo1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(238, 37, 12)));

        campo2.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.foreground"));
        campo2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        campo2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(237, 112, 23)));

        campo3.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.foreground"));
        campo3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        campo3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(251, 249, 10)));

        campo4.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.foreground"));
        campo4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        campo4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(95, 255, 0)));

        campo5.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.foreground"));
        campo5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        campo5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(55, 133, 23)));

        campo6.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.foreground"));
        campo6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        campo6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(24, 192, 246)));

        campo7.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.foreground"));
        campo7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        campo7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(33, 24, 229)));

        campo8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.foreground"));
        campo8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        campo8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(201, 20, 229)));

        labelcampo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelcampo1.setBorder(null);

        labelaviso.setFont(new java.awt.Font("Cantarell", 1, 12)); // NOI18N

        jButton1.setText("fechar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(47, 47, 47))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(labelcampo1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(47, 47, 47)
                                    .addComponent(jLabel1))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(33, 33, 33)
                                    .addComponent(btn_primElem))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(123, 123, 123)
                                    .addComponent(labelaviso))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btn_rem_pf, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(campo_elemPF, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btn_add_pf, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(32, 32, 32)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(campo8, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campo1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campo0, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campo2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campo3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campo4, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campo5, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campo6, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campo7, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(campo0, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campo1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campo2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campo3, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campo4, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campo5, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campo6, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campo7, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campo8, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(btn_primElem)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelcampo1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(labelaviso)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campo_elemPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_add_pf)
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_rem_pf)
                            .addComponent(jButton1))))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_add_pfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_add_pfActionPerformed
       
       
        
        if (tipoLista == "Pilha"){
            
           
            
        
        int elem = Integer.parseInt(campo_elemPF.getText());
       pilha.Insere(elem);
       
       int n = 0;
       int t = 0;
            
            while(t < 9){
                
                quadrados.get(t).setText(null);
                t++;
                
            }
       while (n < pilha.getTamanho()){
           String elemento = Integer.toString(pilha.Elemento(n));
           quadrados.get(n).setText(elemento);
           n++;
       }}
        
        if (tipoLista == "Fila"){
            
            
            
         
       int elem = Integer.parseInt(campo_elemPF.getText());
       fila.Insere(elem);
       int n = 0;
       int t = 0;
            
            while(t < 9){
                
                quadrados.get(t).setText(null);
                t++;
                
            }
       while (n < fila.getTamanho()){
           String elemento = Integer.toString(fila.Elemento(n));
           quadrados.get(n).setText(elemento);
           n++;
       }
            
        }
        
        
    }//GEN-LAST:event_btn_add_pfActionPerformed

    private void btn_rem_pfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_rem_pfActionPerformed
        
        
        
        if (tipoLista == "Pilha"){
            
            if (pilha.getTamanho() == 0){
            
                
             labelaviso.setText("Pilha vazia!");
             return;
                
            }
        
        
       pilha.Remove();
       int n = 0;
       int t = 0;
            
            while(t < 9){
                
                quadrados.get(t).setText(null);
                t++;
                
            }
       while (n < pilha.getTamanho()){
           String elemento = Integer.toString(pilha.Elemento(n));
           quadrados.get(n).setText(elemento);
           n++;
       }}
        
        if (tipoLista == "Fila"){
            
            if (fila.getTamanho() <= 0){
            
                
             labelaviso.setText("Fila vazia!");
             return;
                
            }
         
       
       fila.Remove();
       int n = 0;
       int t = 0;
            
            while(t < 9){
                
                quadrados.get(t).setText(null);
                t++;
                
            }
       while (n < fila.getTamanho()){
           String elemento = Integer.toString(fila.Elemento(n));
           quadrados.get(n).setText(elemento);
           n++;
       }
            
        }
        
    }//GEN-LAST:event_btn_rem_pfActionPerformed

    private void btn_primElemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_primElemActionPerformed
        
        String primeiro = "";
        
        if (tipoLista == "Fila"){
            
            primeiro = Integer.toString(fila.Primeiro());
            
        }
        
        if (tipoLista == "Pilha"){
            
            primeiro = Integer.toString(pilha.Elemento(0));
            
        }
        
       
        labelcampo1.setText(primeiro);
    }//GEN-LAST:event_btn_primElemActionPerformed

    private void campo_elemPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campo_elemPFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campo_elemPFActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Projeto_ED_UI().setVisible(true);
                
                
                
                
            }
            
            
        });
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     * 
     * 
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_add_pf;
    private javax.swing.JButton btn_primElem;
    private javax.swing.JButton btn_rem_pf;
    private javax.swing.JLabel campo0;
    private javax.swing.JLabel campo1;
    private javax.swing.JLabel campo2;
    private javax.swing.JLabel campo3;
    private javax.swing.JLabel campo4;
    private javax.swing.JLabel campo5;
    private javax.swing.JLabel campo6;
    private javax.swing.JLabel campo7;
    private javax.swing.JLabel campo8;
    private javax.swing.JTextField campo_elemPF;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel labelaviso;
    private javax.swing.JLabel labelcampo1;
    // End of variables declaration//GEN-END:variables
}
